class bombel_msg:
	ORDER_LENGTH =					11
	#MSG TYPE
	MSG_HW_CONFIG =					1
	MSG_JOINT_SPACE =				2
	MSG_OPERATION_SPACE =			3

	#HW TYPE
	HW_MOTORS_ON =					1
	HW_MOTORS_OFF =					2
	HW_FANS_ON =					3
	HW_FANS_OFF =					4

	#RESP TYPE
	RESP_HW_ERROR =					1
	RESP_ORDER_ERROR=				2
	RESP_ROBOT_STATE = 				3
	RESP_ORDER_BUFFER_OVERFLOW=		4


